### ISSUE TITLE
rename project to heroku-redis

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-redis-jsplugin#31]
can we change this project name to `heroku-redis` and change the old one to `heroku-redis-ruby-legacy` or something like that?

**Comment by cyberdelia** [comment]
``heroku-redis`` is already taken.

**Comment by dickeyxxx** [comment]
right, I'm saying we should change that old one to something noting that it's no longer usable

**Comment by dickeyxxx** [comment]
oh nevermind, I thought the other one was the old ruby plugin, looks like it isn't
